### ISSUE TITLE
Conversion is wrong

### ISSUE THREAD

**Issue by alprnbg** [bounswe/bounswe2019group7#119]
Kutay solved the conversion issue with PR #117 but we need to update changes on the server.

**Comment by safakozdek** [comment]
Solution: 

1. Connect EC2 device using pem file I sent earlier.
2. Close ongoing tmux programs.
3. Pull new version of practice-app
4. Deploy it again. 

I am not able to do it for now since I am very busy with my final exams, if there is someone who is available, he/she can contact me for details.
