### ISSUE TITLE
Suggestions for backend, frontend, and android technologies

### ISSUE THREAD

**Issue by SKutayKilic** [bounswe/bounswe2019group7#57]
Suggestions for which languages, frameworks and tools will be used in development of backend, frontend, and mobile side. The suggestions will be written under this issue as comments. After the suggestions, people will do some research for the suggested technologies.

Deadline: 17.03.2019 @ 23.59

**Comment by SKutayKilic** [comment]
My suggestions:

Backend: Django, Nodejs, or Ruby on Rails.
Frontend: Angular 2+, React.js, or Vue.js.

**Comment by safakozdek** [comment]
Backend: Django - Simply because I love coding in python.
Frontend: Vue.js - For a long time, I was investigating development of Vue.js even though I have no experience in it. As a result of my research it is good and bad for following reasons:
Pros:
- Easy to learn
- Excellent documentation
- Small size
- Popular 

Cons:
- Small community and lack of resources

**Comment by alprnbg** [comment]
I create a wiki page for suggestions so that we can check out the suggestions later.
