### ISSUE TITLE
Implementation of getEvents() functionality

### ISSUE THREAD

**Issue by safakozdek** [bounswe/bounswe2019group7#87]
Implementation of getEvents() functionality will be done.

Deadline: 27.04.2019, 23:59

**Comment by SKutayKilic** [comment]
Looks fine but there are some little errors:

1) In 'Event/views.py' file the function list returns HtmlResponse but it should be json since it is a rest api.
You can fix it by changing the return line of the function.

2) In Event app the url rooter file('url.py') is missing so you should add that.

3) Also please don't forget to ,add "path('events/', include('events.urls'))" to urlpatterns object(in api_project/urls.py).

**Comment by safakozdek** [comment]
I will be reviewing this, will post results here.

**Comment by safakozdek** [comment]
Event/views.py
line 1,4,5 --- Unnecessary imports, remove them.
line 23  --- Delete unncessary empty lines at the end.

Events/eventcrawler.py
line 4,5 -- Unnecessary imports
line 12 -- Max char limit for a line is 120, you can split string into two pieces, second one could be at the next line. Ex: "String" + "String"
line20,24 -- Delete unnecessary comments
line18 -- change variable name currentdate to currentDate or current_date for readibility
line 41 -- remove redundant paranthesis

Events/tests.py 
Please add test cases.
