### ISSUE TITLE
Work done of summary

### ISSUE THREAD

**Issue by gokdeemir** [bounswe/bounswe2019group7#93]
Work done of summary of milestone will be prepared
Deadline: 11.05.2019, 23:59.

**Comment by alprnbg** [comment]
_After the first milestone, given assignments started to contain more implementation and planning tasks, because eventually we have somehow finished the design part of our project.
First assignment after the first milestone was making our project plan, which is kind of a road map that shows what we have done so far and what we are going to do in a detailed and organized way.
However, the most important thing we have done was an API implementation. We have spent almost 3 weeks for the task and come up with a nice API which has also a front-end. First of all, we decided which functionalities that our API offer in our first API meeting. We have also arranged an online meeting in order to share that functionalities. In short, our plan was not only to implement an API, but also to work together in harmony as a team. Therefore one of our goals was write integrable code. Our API offers some trade-related functionalities like currency exchange calculation and economic events calendar._

You can review and give feedback.
